/*
 * Port_PBcfg.c
 *
 *  Created on: Feb 12, 2024
 *      Author: seif alrahman
 */


#include "Port.h"




#ifndef PORT_PBCFG_H_
#define PORT_PBCFG_H_

/*
* SW Module Version is 1.0.0
*/
#define PORT_PBCFG_SW_MAJOR_VERSION             (1U)
#define PORT_PBCFG_SW_MINOR_VERSION             (0U)
#define PORT_PBCFG_SW_PATCH_VERSION             (0U)

/*
* AUTOSAR Version is 4.0.2 compatible
*/
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* Check compatibility of Port.h AUTOSAR version with
* Port_PBcfg.c AUTOSAR version.
*/
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
    #error "The AR version of Port.h does not match the expected version"
#endif

/* Check compatibility of Port.h SW version with
* Port_PBcfg.c SW version.
*/
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
    #error "The AR version of Port.h does not match the expected version"
#endif
//
//typedef struct
//{
//    uint8 port_num;
//    Port_PinType pin_num;
//    Port_PinDirection direction;
////////////////////////////////////////////////
//    uint8 pin_direction_changeable ;
/////////////////////////////////////////////////
//    Port_InternalResistor resistor;
//*******************************************************//
//    uint8 pin_level_init_value ;
//    Port_PinModeType pin_mode ;
//    uint8 pin_mode_changeable ;
//
//}Port_ConfigType_Pin;
///* Data Structure required for initializing the Port Driver */
//typedef struct {
//    Port_ConfigType_Pin pins[Port_Number_Of_Port_Pins ]  ;
//}Port_ConfigType ;



const Port_ConfigType Port_Configuration= {

         PORT_A,PORT_PIN0,PORT_A_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN1,PORT_A_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN2,PORT_A_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN3,PORT_A_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN4,PORT_A_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN5,PORT_A_PIN_5_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN6,PORT_A_PIN_6_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_A,PORT_PIN7,PORT_A_PIN_7_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
       /*****************************PORT B**************************/
         PORT_B,PORT_PIN0,PORT_B_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN1,PORT_B_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN2,PORT_B_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN3,PORT_B_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN4,PORT_B_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN5,PORT_B_PIN_5_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN6,PORT_B_PIN_6_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_B,PORT_PIN7,PORT_B_PIN_7_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
        /**************************PORT C*************************/
         PORT_C,PORT_PIN0,PORT_C_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN1,PORT_C_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN2,PORT_C_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN3,PORT_C_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN4,PORT_C_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN5,PORT_C_PIN_5_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN6,PORT_C_PIN_6_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_C,PORT_PIN7,PORT_C_PIN_7_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
          /*******************PORT D**********************/
         PORT_D,PORT_PIN0,PORT_D_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN1,PORT_D_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN2,PORT_D_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN3,PORT_D_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN4,PORT_D_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN5,PORT_D_PIN_5_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN6,PORT_D_PIN_6_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_D,PORT_PIN7,PORT_D_PIN_7_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         /*******************PORT E**********************/
         PORT_E,PORT_PIN0,PORT_E_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_E,PORT_PIN1,PORT_E_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_E,PORT_PIN2,PORT_E_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_E,PORT_PIN3,PORT_E_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_E,PORT_PIN4,PORT_E_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         PORT_E,PORT_PIN5,PORT_E_PIN_5_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_INITIAL_MODE,PORT_PIN_MODE_CHANGEABLE,
         /*******************PORT F**********************/
         PORT_F,PORT_PIN0,PORT_F_PIN_0_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_CHANGEABLE,
         PORT_F,PORT_PIN1,PORT_F_PIN_1_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,OFF,STD_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_CHANGEABLE,      //LED
         PORT_F,PORT_PIN2,PORT_F_PIN_2_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_CHANGEABLE,
         PORT_F,PORT_PIN3,PORT_F_PIN_3_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_DOWN,STD_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_CHANGEABLE,
         PORT_F,PORT_PIN4,PORT_F_PIN_4_DIRECTION,PORT_PIN_DIRECTION_CHANGEABLE,PULL_UP,STD_LOW,PORT_PIN_MODE_DIO,PORT_PIN_MODE_CHANGEABLE,        //BUTTON

};
#endif


